
#include "rf1a.h"

// Rf settings for CC430 generated by SmartRF Studio
const RF_SETTINGS rfSettings_fixed = {
    0x29,  // IOCFG2        GDO2 Output Configuration
    0x2E,  // IOCFG1        GDO1 Output Configuration
    0x06,  // IOCFG0        GDO0 Output Configuration
    0x40,  // PKTLEN        Packet Length
    0x00,  // PKTCTRL0      Packet Automation Control
    0x10,  // FREQ2         Frequency Control Word, High Byte
    0xB0,  // FREQ1         Frequency Control Word, Middle Byte
    0x71,  // FREQ0         Frequency Control Word, Low Byte
    0x86,  // MDMCFG4       Modem Configuration
    0x70,  // MDMCFG3       Modem Configuration
    0x32,  // MDMCFG2       Modem Configuration
    0x02,  // MDMCFG1       Modem Configuration
    0x00,  // MCSM1         Main Radio Control State Machine Configuration
    0x00,  // MCSM0         Main Radio Control State Machine Configuration
    0x76,  // FOCCFG        Frequency Offset Compensation Configuration
    0x87,  // WOREVT1       High Byte Event0 Timeout
    0x6B,  // WOREVT0       Low Byte Event0 Timeout
    0xF0,  // WORCTRL       Wake On Radio Control
    0x11,  // FREND0        Front End TX Configuration
    0xE9,  // FSCAL3        Frequency Synthesizer Calibration
    0x2A,  // FSCAL2        Frequency Synthesizer Calibration
    0x00,  // FSCAL1        Frequency Synthesizer Calibration
    0x1F,  // FSCAL0        Frequency Synthesizer Calibration
    0x09,  // TEST0         Various Test Settings
};

